services:
- postgresql
addons:
  postgresql: '9.5'
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database test_db;' -U postgres
language: ruby
rvm:
- 2.5.5
script:
- bundle install --jobs=3 --retry=3
- bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: soh0mGPEiiFiwGEdIQzzkijJzewDTy1B0tOxYGlTaaKD/I5SriFNJtQXhC9CJOjoJpbNhgBwnXkebsR7nXZ53i+tkxgWEZAOVjuhwJEkMJkrrf3x/9hLUjzE3Guo29enmG60GLziAGjBvk0znmYAvJHVSRzo21Qnnhx56odWxy0LTDqgN/5wVjEy/jCtkQrXSnpwzc6smxVHg+QS6fysCceIwuSXrrRHn5brCJhoRi/1kXIEYNbYrbxukg+PpHjPugtRz23fWppbDj/DKc/iqFxhvzF9ns7Ym3/JXrJG5Mmei/4xCt8xEfefIKgVzQCGS2OXM+3/ThQw5vckKc/0JuVv2kYY+QGydW7z7OYeoD2BqHUkZHVphiuUsULOCKwsuMF+EMmgU9NvB6T1uCCQ4Wz/KQf6HSR4JxG2vvWnAl9A+EvlSaJc/vjksHCBhwzarF+BBGQ5uQ+QVIXiCh22WHgJLju/LKBr8X0KfKHV0YTL1ROPxKnVYd6P6/G2tgeCHK5QwuWeNM/xscxxoDkn/4xehZDLMkCkuk3e1H47kAUU7cvDKB/dDh8vp2ul+ZHENzCWOJWq+Esf6jmwlKByo+CsdEo2QnvdEvlRFVxEMB9aTxPT9b40vAQZs1dRXv+H+mJALnV0Ymmt98db8S0jHH8KC9YFP3aMmkfuiXD6yR8=
  app:
    stable: lifetoremindhub
    master: lifetoremindhubdevel
  on:
    repo: eduqg/LifeToRemind