default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  host: <%= ENV.fetch("DB_HOST") { localhost } %>
  username: postgres
  password: <%= ENV.fetch("DB_PASSWORD") { postgres } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ltr_development

test:
  <<: *default
  database: ltr_test

production:
  <<: *default
  database: ltr_production
