default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  port: 5432
  database: ltr
  host: <%= ENV.fetch("DB_HOST") { localhost } %>
  username: <%= ENV.fetch("DB_USER") { postgres } %>
  password: <%= ENV.fetch("LTR_DATABASE_PASSWORD") { postgres } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
