# This file is the docker file for database.yml temporary moved.
# Check build 53 https://travis-ci.org/eduqg/LifeToRemind/builds/601943781 line 1443 if you want help with docker

default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  port: 5432
  host: <%= ENV.fetch("DB_HOST") || localhost %>
  username: postgres
  password: <%= ENV.fetch("DB_PASSWORD") || postgres %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") || 5 %>

development:
  <<: *default
  database: ltr_development

test:
  <<: *default
  database: ltr_test

production:
  <<: *default
  database: ltr_production
