default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ltr_development

test:
  <<: *default
  database: ltr_test

production:
  <<: *default
  database: ltr_production
  username: ltr
  password: <%= ENV['LTR_DATABASE_PASSWORD'] %>
